// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuV9Puengh1TuyumoxrKMLF47Sz7FSsgE',
    appId: '1:375457950030:web:b46b6f556f5f528722161f',
    messagingSenderId: '375457950030',
    projectId: 'orthoconnect-app',
    authDomain: 'orthoconnect-app.firebaseapp.com',
    storageBucket: 'orthoconnect-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIN1AeFMpXM1Vc0Nwt4H2nWkpXwXb0gI8',
    appId: '1:375457950030:android:f83f0802f5d5dc2022161f',
    messagingSenderId: '375457950030',
    projectId: 'orthoconnect-app',
    storageBucket: 'orthoconnect-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjTJuN1UkfV1mYKDgn5CbsHLKTpaB_tHs',
    appId: '1:375457950030:ios:f7a188d1db4a6c5e22161f',
    messagingSenderId: '375457950030',
    projectId: 'orthoconnect-app',
    storageBucket: 'orthoconnect-app.firebasestorage.app',
    iosBundleId: 'com.example.rootedpath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjTJuN1UkfV1mYKDgn5CbsHLKTpaB_tHs',
    appId: '1:375457950030:ios:f7a188d1db4a6c5e22161f',
    messagingSenderId: '375457950030',
    projectId: 'orthoconnect-app',
    storageBucket: 'orthoconnect-app.firebasestorage.app',
    iosBundleId: 'com.example.rootedpath',
  );

}